### ISSUE TITLE
Add the ability to disable automatic symlink

### ISSUE THREAD

**Issue by Shatur** [mikehardy/buildcache-action#25]
Hi! Thank you for the awesome action.
Could you add an option to disable symlinks? I use this action to build CMake C++ projects with different compilers and use it by simply passing `-D CMAKE_C_COMPILER_LAUNCHER=buildcache` to configure arguments. And when I need clang as a compiler, then I have problems with duplicate buildcache.

**Comment by mikehardy** [comment]
Hi there! I'd be happy to take a PR that implements it

**Comment by mikehardy** [comment]
Worth noting that my main use case for this action was because ccache did not support "ivfsoverlay" in Xcode for iOS projects so ccache-action was inefficient vs buildcache + buildcache-action here.

ccache now supports this mode and is thus a great deal faster than buildcache, so I probably won't even be using my own action (this one here) anymore in practice.

So I'm going to close this as I'll fix errors but enhancement requests aren't something I just want to leave sitting on the issues list.

As mentioned though, if buildcache is superior for you and you'd like this action to support it, I'd be happy to take a PR
