### ISSUE TITLE
Pointers for supporting msvc

### ISSUE THREAD

**Issue by eike-fokken** [mikehardy/buildcache-action#26]
Hi!

Could you give me some pointers, what I must do, to change this action to work with msvc under windows?

**Comment by mikehardy** [comment]
No sorry - it's not a usecase of mine, though I'd be happy to take a PR for it.
Worth noting that my main use case for this action was because ccache did not support "ivfsoverlay" in Xcode for iOS projects so ccache-action was inefficient vs buildcache + buildcache-action here.

ccache now supports this mode and is thus a great deal faster than buildcache, so I probably won't even be using my own action (this one here) anymore in practice.

So I'm going to close this as I'll fix errors but enhancement requests aren't something I just want to leave sitting on the issues list.

As mentioned though, if buildcache is superior for you and you'd like this action to support it, I'd be happy to take a PR

**Comment by eike-fokken** [comment]
I understand.
