### ISSUE TITLE
can i use with gym

### ISSUE THREAD

**Issue by HassnAsaad** [mikehardy/buildcache-action#54]
Hi
I'm using Fastlane and building ios with gym and I cant quietly figure out how to make it work I will appreciate it if you can help me
thanks

**Comment by mikehardy** [comment]
you will need to either set the environment variables CC//LD to "clang" and CPLUSPLUS/LDPLUSPLUS to just "clang++" so that xcodebuild does not use absolute paths and thus picks up on the symbolically linked clang/clang++ in your path from buildcache, or you need to alter your Podfile to change the same variables in build settings to the clang / clang++ non-path names

Then the compiler wrapper is called instead of the actual binary, giving buildcacahe a chance to work
